version: 2.1

jobs:
  aqua-scanner:
    docker:
      - image: aquasec/aqua-scanner
    steps:
      - checkout
      - run: |
          export TRIVY_RUN_AS_PLUGIN=aqua
          trivy fs --security-checks config,vuln,secret .
          # To customize which severities to scan for, add the following flag: --severity UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL
          # To enable SAST scanning, add: --sast
          # To enable npm/dotnet non-lock file scanning, add: --package-json / --dotnet-proj

workflows:
  aqua-scan:
    jobs:
      - aqua-scanner
